apiVersion: v1
kind: Pod
metadata:
  name: nginx-ebs
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-storage
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: ebs-pvc
